### PR TITLE
Documentation building using travis-sphinx

### PR DESCRIPTION
**Pull request by davidwyld**
To be merged after the `pytest` branch.

Similarly to [deepQuest classic](https://github.com/sheffieldnlp/deepQuest) this uses [travis-sphinx](https://github.com/Syntaf/travis-sphinx) to build the docs to the `gh-pages` branch of this repo.

**Note**:
- Currently, this allows the master, deepquest-dev, and newdocs branches to build the docs on push. newdocs should be removed on merging.
- Also currently, travis-sphinx is authenticated to build the docs using a PAT from my account, since this repo is going to be handed over very soon, this should be changed to someone else's. (or even better, using readthedocs instead) @fredblain it makes sense for this to be yours. Let me know if this is okay and I can tell you what you need to do.

Below, all the commits from pytest and newdocs are showing, the relevant ones to this PR start at 
66e3ff7

### CODE REVIEW

**Comment by davidwyld** [comment]
@fredblain please review this PR so it can be merged.

**Comment by davidwyld** [comment]
Since this is my last day working on deepQuest for now, I'm going to remove my personal access token (PAT) from the travis settings for this repo. I don't want travis for this repo to have write access to everything that I do after today.

In order to facilitate the docs building, @fredblain you will need to add your PAT by following the instructions here: https://github.com/Syntaf/travis-sphinx#obtaining-a-personal-access-token

Let me know if you have any questions.

**Review by drj11 — APPROVED** [review]
it's fine i guess?

**Review by fredblain — APPROVED** [review]

**Comment by fredblain** [comment]
> Since this is my last day working on deepQuest for now, I'm going to remove my personal access token (PAT) from the travis settings for this repo. I don't want travis for this repo to have write access to everything that I do after today.
> 
> In order to facilitate the docs building, @fredblain you will need to add your PAT by following the instructions here: https://github.com/Syntaf/travis-sphinx#obtaining-a-personal-access-token
> 

This won't be necessary, as it is already set up for the current release of deepQuest.

**Pull request merged**
