### PR TITLE
make seed setting a command line option

### PR DESCRIPTION
**Pull request by davidwyld**
This will make seed setting an option from the command line, run as follows:
```shell
dq train -s 42 -c config.yml .......
```
or
```shell
python __main__.py train -s 42 -c config.yml .......
```
omitting the -s option leaves the seed setting as random, for normal training.

### CODE REVIEW

**Comment by davidwyld** [comment]
Btw, both travis checks have passed, not sure why it's showing as 1 pending.

**Review by fredblain — CHANGES_REQUESTED** [review]
Let's not use `-s` as it is usually used for identifying the "source" language in many NLP tools. 
Overall, I would prefer having ```seed: 42``` by default in every config file we release, as it does not make sense to not fix the seed in the first place.

**Comment by davidwyld** [comment]
I'm a little confused by this comment:
> it does not make sense to not fix the seed in the first place.

I had thought that you might want to run with random results in normal operation, but maybe fix the seed for development, is that not the case?
To be clear, if the seed is set to any particular value, the training output will always be the same.

**Comment by fredblain** [comment]
> By fixing the seed, you ensure that the 'random' numbers generated in your ML algorithm are exactly the same, every time it is ran. This means your experiments/results will be exactly reproducible by yourself and others.

This is not from me, but I agree.

**Comment by davidwyld** [comment]
Okay, @fredblain I've changed this (e59ee66) as per your request, so hopefully these will pass the tests successfully. Let me know if you'd rather do this any differently.

**Comment by fredblain** [comment]
IMO, `set_seed` should be responsible for setting the seed, and nothing else (i.e. it should not be responsible for updating all parameters in addition to the seed).
Also, I am not in favor of having a default config file for each implemented model. Either each model defines its own default parameters in its constructor, or the meta class QEModel defines the default parameters, or the default parameters are defined under `/utils` (could be in `utils.py` itself, along with the `update_parameters` function, since part of the parameters are related to NMT-Keras, and not the models themselves).

**Comment by davidwyld** [comment]
@fredblain `set_seed` in `__main__.py` doesn't do anything other than set the seed, but if you want it to be in the config file, then we need to load the config from there (or from a pkl, or with changes from the command line).

+ let's talk about the default parameters later.

**Comment by davidwyld** [comment]
Need to add seed logging.

**Pull request merged**
